name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest

    environment:
      name: rubygems.org
      url: https://rubygems.org/gems/importance

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.3.5

      - name: Configure trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v2.1.0

      - name: Build gem
        run: gem build importance.gemspec

      - name: Push gem
        run: gem push importance-*.gem
